### ISSUE TITLE
Mantis vulnerability found

### ISSUE THREAD

**Issue by nolan124** [dregad/mantisbt#9]
Hello, dear developers, I found a mantis arbitrary file reading vulnerability, please contact me if you receive it, my email is
nolan124x@gmail.com, contact me and I will send you the details of the vulnerability, thank you

**Comment by dregad** [comment]
@nolan124 Thanks for your message. 

Instead of using e-mail, the best would be for you to open a _private_ issue at https://mantisbt.org/bugs so only Devs will see it. Please include all necessary details, including CVE ID if you have one and if not we can take care of requesting it (in this case, indicate how you would like to be credited for the finding).

**Comment by nolan124** [comment]
> 在这种情况下，请注明您希望如何为此次发现功劳）


Thank you for your reply. I found a bug in the version prior to mantis 1.1.6. Can you help me get the cve number?
